version: '3.8'
services:
  nginx:
    ports:
      - "80:80"
  node-docker-app:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parrallelism: 2
        delay: 15s
        failure_action: rollback
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}