version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-docker-app
  node-docker-app:
    build: .
    environment:
      - PORT=8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dibyajyotimishra
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis


volumes:
  mongo-db:
